kind: Service
apiVersion: v1
metadata:
  name: lab-hello-service
  namespace: lab
spec:
  selector:
    app: lab-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer