apiVersion: v1
kind: Pod
metadata:
  name: lab-hello
  namespace: lab
spec:
  containers:
  - name: lab-k8s-openresty
    image: lab-k8s-openresty:v1
    resources:
      limits:
        memory: "200Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
