apiVersion: v1
kind: Pod
metadata:
  namespace: lab
  name: lab-hello-pod
  labels:
    app: lab-hello
spec:
  containers:
  - name: lab-hello-openresty
    image: lab-k8s-openresty:v1
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /etc/nginx/conf.d
      name: nginx-config
  volumes:
  - name: nginx-config
    hostPath:
      path: /Users/tom/Repository/lab/etc/nginx/conf.d

---

apiVersion: v1
kind: Pod
metadata:
  namespace: lab
  name: lab-hello-pod2
  labels:
    app: lab-hello
spec:
  containers:
  - name: lab-hello-openresty
    image: lab-k8s-openresty:v1
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /etc/nginx/conf.d
      name: nginx-config
  volumes:
  - name: nginx-config
    hostPath:
      path: /Users/tom/Repository/lab/etc/nginx/conf2.d

---

apiVersion: v1
kind: Service
metadata:
  name: lab-hello-service
  namespace: lab
spec:
  selector:
    app: lab-hello
  ports:
    - port: 80
  type: LoadBalancer