version: '3'
services:
  lab.rabbitmq.work.net:
      image: rabbitmq
      container_name: lab_rabbitmq
      restart: always
      ports:
        - "5673:5672"
        - "15673:15672"
  lab.php.work.net:
      build: ../../../container/centos_php7_fpm
      container_name: lab_php
      restart: always
      links:
        - lab.rabbitmq.work.net:rabbitmq.work.net
      ports:
        - "9100:9000"
      volumes:
        - ../../../htdocs:/data1/htdocs
        - ../../../app:/data1/app
        - ../../../log:/data1/log
        - ../../php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
        - ../../php/php.ini:/usr/local/php/lib/php.ini
      extra_hosts:
        - "php.work.net:127.0.0.1"
      environment:
        COMPOSER_PROCESS_TIMEOUT: 3000
        COMPOSER_MEMORY_LIMIT: -1