version: '3'
services:
  rabbitmq.lab.net:
      image: rabbitmq
      container_name: lab_rabbitmq
      restart: always
      networks:
        - lab-net
      environment:
        RABBITMQ_ERLANG_COOKIE: PTDGWIUEPHBHXWRRWFXX
        # RABBITMQ_USE_LONGNAME: 1
        # RABBITMQ_NODENAME: rabbit
      expose:
        - "5672"
        - "15672"
  rabbitmq2.lab.net:
      image: rabbitmq
      container_name: lab_rabbitmq2
      restart: always
      networks:
        - lab-net
      environment:
        RABBITMQ_ERLANG_COOKIE: PTDGWIUEPHBHXWRRWFXX
        # RABBITMQ_USE_LONGNAME: 1
        # RABBITMQ_NODENAME: rabbit
      expose:
        - "5672"
        - "15672"

  redis.lab.net:
      image: redis
      container_name: lab_redis
      restart: always
      networks:
         - lab-net

  php.lab.net:
      build: ../../../container/centos_php7_fpm
      container_name: lab_php
      restart: always
      networks:
        - lab-net
      ports:
        - "9100:9000"
      volumes:
        - ../../../htdocs:/data1/htdocs
        - ../../../app:/data1/app
        - ../../../log:/data1/log
        - ../../php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
        - ../../php/php.ini:/usr/local/php/lib/php.ini
      environment:
        COMPOSER_PROCESS_TIMEOUT: 3000
        COMPOSER_MEMORY_LIMIT: -1
networks:
  lab-net: