version: '3.5'
services:
  lvs:
      build: ./
      restart: always
      privileged: true
      container_name: lvs
      cap_add:
        - ALL
      networks:
        lab-com:
networks:
  lab-com:
    name: lab-com